"use client";
import {useEffect,useMemo,useState} from "react";

type EventItem={id:number;serviceDate:string;startTime:string;endTime:string;household:string;chef:string;packageName:string;location:string;status:string;notes:string;createdAt:string;updatedAt:string};
const empty=(date:string):Omit<EventItem,"id"|"createdAt"|"updatedAt">=>({serviceDate:date,startTime:"09:00",endTime:"12:00",household:"",chef:"Unassigned",packageName:"Weekly",location:"",status:"scheduled",notes:""});
const chefs=["Unassigned","Maya Chen","Jordan Lee","Alex Morgan","Sam Rivera"];
const packages=["Essential · 6","Classic · 8","Weekly · 12","Couples · 16","Household · 20","Family · 24"];
const pad=(n:number)=>String(n).padStart(2,"0");
const iso=(date:Date)=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;

export default function AdminCalendar(){
  const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
  const [events,setEvents]=useState<EventItem[]>([]),[selectedDate,setSelectedDate]=useState(()=>iso(new Date())),[editing,setEditing]=useState<(EventItem|ReturnType<typeof empty>)|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const first=iso(new Date(month.getFullYear(),month.getMonth(),1)),last=iso(new Date(month.getFullYear(),month.getMonth()+1,0));
  useEffect(()=>{setLoading(true);setError("");fetch(`/api/schedule?start=${first}&end=${last}`).then(async response=>{if(response.status===401){window.location.href="/signin-with-chatgpt?return_to=%2Fportal";throw new Error("signin")}if(!response.ok)throw new Error("load");return response.json()}).then(setEvents).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[first,last]);
  const days=useMemo(()=>{const leading=new Date(month.getFullYear(),month.getMonth(),1).getDay(),count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();return[...Array.from({length:leading},()=>null),...Array.from({length:count},(_,index)=>index+1)]},[month]);
  const selected=events.filter(event=>event.serviceDate===selectedDate);
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!editing)return;const isExisting="id" in editing;const response=await fetch("/api/schedule",{method:isExisting?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(editing)});if(response.status===401){window.location.href="/signin-with-chatgpt?return_to=%2Fportal";return}if(!response.ok){setError("save");return}const saved=await response.json() as EventItem;setEvents(current=>isExisting?current.map(item=>item.id===saved.id?{...item,...saved}:item):[...current,saved].sort((a,b)=>(a.serviceDate+a.startTime).localeCompare(b.serviceDate+b.startTime)));setSelectedDate(saved.serviceDate);setEditing(null)}
  async function remove(id:number){if(!window.confirm("Remove this scheduled visit?"))return;const response=await fetch(`/api/schedule?id=${id}`,{method:"DELETE"});if(response.ok)setEvents(current=>current.filter(item=>item.id!==id))}
  const update=(key:string,value:string)=>setEditing(current=>current?{...current,[key]:value}:current);
  return <>
    <header className="page-head"><div><h1>Operations calendar</h1><p>Schedule visits, assign chefs, and keep every household organized.</p></div><button className="calendar-add" onClick={()=>setEditing(empty(selectedDate))}>+ Schedule visit</button></header>
    <div className="page-body"><div className="calendar-summary"><div><small>THIS MONTH</small><strong>{events.length}</strong><span>scheduled visits</span></div><div><small>UNASSIGNED</small><strong>{events.filter(event=>event.chef==="Unassigned").length}</strong><span>need chef coverage</span></div><div><small>CONFIRMED</small><strong>{events.filter(event=>event.status==="confirmed").length}</strong><span>households ready</span></div><div><small>COMPLETED</small><strong>{events.filter(event=>event.status==="completed").length}</strong><span>visits finished</span></div></div>
      {error==="signin"?<div className="schedule-signin"><h2>Staff sign-in required</h2><p>Sign in before opening or changing the operations calendar.</p><a href="/signin-with-chatgpt?return_to=%2Fportal">Sign in to continue →</a></div>:<div className="ops-calendar-layout"><section className="ops-calendar"><header><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><div><small>OPERATIONS SCHEDULE</small><h2>{month.toLocaleString("en-US",{month:"long",year:"numeric"})}</h2></div><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></header><div className="weekday-row">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(day=><b key={day}>{day}</b>)}</div><div className="month-grid">{days.map((day,index)=>day===null?<span className="empty-day" key={`empty-${index}`}/>:<button key={day} className={`${selectedDate===iso(new Date(month.getFullYear(),month.getMonth(),day))?"selected":""} ${iso(new Date())===iso(new Date(month.getFullYear(),month.getMonth(),day))?"today":""}`} onClick={()=>setSelectedDate(iso(new Date(month.getFullYear(),month.getMonth(),day)))}><strong>{day}</strong><div>{events.filter(event=>event.serviceDate===iso(new Date(month.getFullYear(),month.getMonth(),day))).slice(0,3).map(event=><i className={`event-dot ${event.status}`} key={event.id}>{event.startTime} {event.household}</i>)}</div>{events.filter(event=>event.serviceDate===iso(new Date(month.getFullYear(),month.getMonth(),day))).length>3?<small>+{events.filter(event=>event.serviceDate===iso(new Date(month.getFullYear(),month.getMonth(),day))).length-3} more</small>:null}</button>)}</div></section>
        <aside className="day-agenda"><header><div><small>DAY SCHEDULE</small><h2>{new Date(`${selectedDate}T12:00:00`).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"})}</h2></div><button onClick={()=>setEditing(empty(selectedDate))}>+</button></header>{loading?<p className="agenda-empty">Loading calendar…</p>:selected.length===0?<div className="agenda-empty"><strong>No visits scheduled</strong><p>This day is open. Add a household when you&apos;re ready.</p><button onClick={()=>setEditing(empty(selectedDate))}>Schedule a visit</button></div>:<div className="agenda-list">{selected.map(event=><article key={event.id}><span className={`agenda-time ${event.status}`}>{event.startTime}</span><div><StatusLabel status={event.status}/><h3>{event.household}</h3><p>{event.packageName} · {event.location||"Location pending"}</p><small>{event.chef}</small><div><button onClick={()=>setEditing(event)}>Edit</button><button onClick={()=>remove(event.id)}>Remove</button></div></div></article>)}</div>}</aside></div>}
    </div>
    {editing?<div className="schedule-modal" role="dialog" aria-modal="true" aria-labelledby="schedule-title"><form onSubmit={save}><button className="schedule-close" type="button" onClick={()=>setEditing(null)}>×</button><small>DRIFTLINE OPERATIONS</small><h2 id="schedule-title">{"id" in editing?"Edit scheduled visit":"Schedule a visit"}</h2><div className="schedule-form-grid"><label>Date<input type="date" value={editing.serviceDate} onChange={e=>update("serviceDate",e.target.value)} required/></label><label>Status<select value={editing.status} onChange={e=>update("status",e.target.value)}><option value="scheduled">Scheduled</option><option value="confirmed">Confirmed</option><option value="shopping">Shopping</option><option value="in-progress">In progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label>Start time<input type="time" value={editing.startTime} onChange={e=>update("startTime",e.target.value)} required/></label><label>End time<input type="time" value={editing.endTime} onChange={e=>update("endTime",e.target.value)}/></label><label>Household<input value={editing.household} onChange={e=>update("household",e.target.value)} placeholder="Barella household" required/></label><label>Location<input value={editing.location} onChange={e=>update("location",e.target.value)} placeholder="Astoria"/></label><label>Assigned chef<select value={editing.chef} onChange={e=>update("chef",e.target.value)}>{chefs.map(chef=><option key={chef}>{chef}</option>)}</select></label><label>Package<select value={editing.packageName} onChange={e=>update("packageName",e.target.value)}>{packages.map(item=><option key={item}>{item}</option>)}</select></label></div><label>Operations notes<textarea value={editing.notes} onChange={e=>update("notes",e.target.value)} placeholder="Access instructions, allergy flags, shopping timing, or coverage notes."/></label><button className="schedule-save">{"id" in editing?"Save changes":"Add to calendar"} →</button></form></div>:null}
  </>;
}
function StatusLabel({status}:{status:string}){return <span className={`calendar-status ${status}`}>{status.replace("-"," ")}</span>}
