export type GroceryCategory = "Meat & seafood" | "Produce" | "Dairy & eggs" | "Grains & bakery" | "Pantry";
export type GroceryItem={key:string;name:string;quantity:number|null;unit:string;display:string;category:GroceryCategory;dishes:string[]};
type GroceryDish={title:string;ingredients:string[];servings?:number;portions?:number};
const fractions:Record<string,number>={"¼":.25,"½":.5,"¾":.75,"⅓":1/3,"⅔":2/3,"⅛":.125,"⅜":.375,"⅝":.625,"⅞":.875};
const units:Record<string,string>={lb:"lb",lbs:"lb",pound:"lb",pounds:"lb",oz:"oz",ounce:"oz",ounces:"oz",cup:"cup",cups:"cup",tbsp:"tbsp",tablespoon:"tbsp",tablespoons:"tbsp",tsp:"tsp",teaspoon:"tsp",teaspoons:"tsp",clove:"clove",cloves:"clove",can:"can",cans:"can",package:"package",packages:"package",bunch:"bunch",bunches:"bunch",tortilla:"tortilla",tortillas:"tortilla",fillet:"fillet",fillets:"fillet",noodle:"noodle",noodles:"noodle"};
function amount(value:string){const vulgar=value.match(/[¼½¾⅓⅔⅛⅜⅝⅞]/)?.[0],whole=Number(value.replace(/[¼½¾⅓⅔⅛⅜⅝⅞]/g,"").trim()||0);if(vulgar)return whole+fractions[vulgar];if(value.includes("/")){const parts=value.includes(" ")?value.split(/\s+/,2):["0",value],[top,bottom]=parts[1].split("/").map(Number);return Number(parts[0])+top/bottom}return Number(value)}
const clean=(value:string)=>value.replace(/,\s*(minced|chopped|diced|drained|grated|divided).*$/i,"").replace(/\s+/g," ").trim();
function category(name:string):GroceryCategory{const value=name.toLowerCase();if(/chicken|turkey|beef|steak|pork|ham|lamb|salmon|cod|fish|shrimp|tuna|crab|sausage|tofu/.test(value))return"Meat & seafood";if(/garlic|onion|lemon|lime|ginger|parsley|cilantro|dill|rosemary|spinach|potato|tomato|pepper|zucchini|broccoli|carrot|celery|mushroom|cabbage|kale|corn|peas|beans|chiles|vegetable|apple|pear|bok choy|snap peas|parsnip|cucumber|eggplant|squash/.test(value))return"Produce";if(/milk|cream|yogurt|cheese|parmesan|mozzarella|butter|egg/.test(value))return"Dairy & eggs";if(/rice|pasta|penne|orzo|noodle|quinoa|couscous|barley|polenta|tortilla|farro|bread/.test(value))return"Grains & bakery";return"Pantry"}
function quantity(value:number,unit=""){if(/^(clove|tortilla|fillet|noodle)$/.test(unit))return String(Math.max(1,Math.round(value)));const whole=Math.floor(value),decimal=value-whole,candidates:Array<[number,string]>=[[0,""],[.125,"⅛"],[.25,"¼"],[1/3,"⅓"],[.375,"⅜"],[.5,"½"],[.625,"⅝"],[2/3,"⅔"],[.75,"¾"],[.875,"⅞"],[1,""]],nearest=candidates.reduce((best,item)=>Math.abs(item[0]-decimal)<Math.abs(best[0]-decimal)?item:best);if(nearest[0]===1)return String(whole+1);return`${whole||""}${nearest[1]}`||"0"}
const unitLabel=(unit:string,value:number)=>/^(lb|oz|tbsp|tsp)$/.test(unit)||value===1?unit:`${unit}s`;
const amountPattern="(\\d+(?:\\.\\d+)?(?:\\s+\\d+\\/\\d+)?|\\d+\\/\\d+|\\d*[¼½¾⅓⅔⅛⅜⅝⅞])";
function parse(raw:string){const value=raw.trim(),count=value.match(new RegExp(`^${amountPattern}\\s+(.+\\s+(tortillas?|fillets?|lasagna noodles))$`,"i"));if(count){const unit=/noodles$/i.test(count[3])?"noodle":units[count[3].toLowerCase()];return{quantity:amount(count[1]),unit,name:clean(count[2])}}const match=value.match(new RegExp(`^${amountPattern}\\s+([^\\s]+)\\s+(.+)$`));if(!match)return{quantity:null,unit:"",name:clean(raw)};const unit=units[match[2].toLowerCase().replace(/[.,]$/,"")];return unit?{quantity:amount(match[1]),unit,name:clean(match[3])}:{quantity:null,unit:"",name:clean(raw)}}
function factor(dish:GroceryDish){const base=Math.max(1,dish.servings||12),target=Math.max(1,dish.portions||base);return target/base}
const displayQuantity=(value:number,unit:string,name:string)=>/^(tortilla|fillet|noodle)$/.test(unit)?`${quantity(value,unit)} ${name}`:`${quantity(value,unit)} ${unitLabel(unit,value)} ${name}`;
export function scaleIngredients(ingredients:string[],baseServings:number,portions:number){const scale=Math.max(1,portions)/Math.max(1,baseServings);return ingredients.map(raw=>{const item=parse(raw),scaled=item.quantity===null?null:item.quantity*scale;return scaled===null?raw.trim():displayQuantity(scaled,item.unit,item.name)})}
export function buildGroceryList(dishes:GroceryDish[]):GroceryItem[]{const map=new Map<string,GroceryItem>();for(const dish of dishes)for(const raw of dish.ingredients){const item=parse(raw),scaled=item.quantity===null?null:item.quantity*factor(dish),key=`${item.unit||"item"}:${item.name.toLowerCase()}`,existing=map.get(key);if(existing){if(existing.quantity!==null&&scaled!==null)existing.quantity+=scaled;if(!existing.dishes.includes(dish.title))existing.dishes.push(dish.title)}else map.set(key,{key,name:item.name,quantity:scaled,unit:item.unit,display:raw.trim(),category:category(item.name),dishes:[dish.title]})}return[...map.values()].map(item=>({...item,display:item.quantity===null?item.name:displayQuantity(item.quantity,item.unit,item.name)})).sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name))}
