"use client";

import {useMemo,useState} from "react";
import "./LabelPrinter.css";
import "./LabelPrinterPreview.css";

type LabelDish={title:string;portions:number;allergens:string[];reheating:string;safety:string;storage:string};
const dateLabel=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});
const addDays=(value:string,days:number)=>{const date=new Date(`${value}T12:00:00`);date.setDate(date.getDate()+days);return date.toISOString().slice(0,10)};

export default function LabelPrinter({household,serviceDate,dishes}:{household:string;serviceDate:string;dishes:LabelDish[]}){
  const[counts,setCounts]=useState<Record<number,number>>(()=>Object.fromEntries(dishes.map((dish,index)=>[index,dish.portions]))),[prepared,setPrepared]=useState(serviceDate),[useBy,setUseBy]=useState(addDays(serviceDate,4)),[instructions,setInstructions]=useState<Record<number,string>>(()=>Object.fromEntries(dishes.map((dish,index)=>[index,dish.reheating]))),[previewIndex,setPreviewIndex]=useState(0),[printIndex,setPrintIndex]=useState<number|null>(null);
  const labels=useMemo(()=>dishes.flatMap((dish,index)=>Array.from({length:counts[index]||0},(_,copy)=>({dish,index,copy,count:counts[index]}))),[dishes,counts]);
  const updateCount=(index:number,amount:number)=>setCounts(current=>({...current,[index]:Math.min(50,Math.max(0,(current[index]||0)+amount))}));
  const print=(index:number|null)=>{setPrintIndex(index);window.setTimeout(()=>window.print(),50)},previewDish=dishes[previewIndex],printLabels=printIndex===null?labels:[{dish:dishes[printIndex],index:printIndex,copy:0,count:1}];
  return <section className="label-station"><header><div><small>CONTAINER LABELS</small><h2>Print meal labels</h2><p>Preview or reprint one dish at any time, or print the complete batch.</p></div><button type="button" disabled={!labels.length} onClick={()=>print(null)}>Print all {labels.length}</button></header><div className="label-dates"><label>Prepared<input type="date" value={prepared} onChange={event=>setPrepared(event.target.value)}/></label><label>Use by<input type="date" value={useBy} onChange={event=>setUseBy(event.target.value)}/></label></div><div className="label-dishes">{dishes.map((dish,index)=><details className={previewIndex===index?"previewing":""} key={`${dish.title}-${index}`}><summary><div><strong>{dish.title}</strong><small>{counts[index]||0} labels · {dish.portions} planned portions</small></div><span className="label-count"><button type="button" onClick={event=>{event.preventDefault();updateCount(index,-1)}} aria-label={`Remove one ${dish.title} label`}>−</button><b>{counts[index]||0}</b><button type="button" onClick={event=>{event.preventDefault();updateCount(index,1)}} aria-label={`Add one ${dish.title} label`}>+</button></span><span className="label-actions"><button type="button" onClick={event=>{event.preventDefault();setPreviewIndex(index)}}>Preview</button><button type="button" onClick={event=>{event.preventDefault();setPreviewIndex(index);print(index)}}>Print 1</button></span><i>Customize ⌄</i></summary><label>Reheating directions<textarea value={instructions[index]||""} onChange={event=>setInstructions(current=>({...current,[index]:event.target.value}))}/></label></details>)}</div><div className="label-preview"><small>PREVIEWING · {previewDish?.title.toUpperCase()}</small>{previewDish?<MealLabel household={household} prepared={prepared} useBy={useBy} dish={previewDish} copy={0} count={Math.max(1,counts[previewIndex]||0)} reheating={instructions[previewIndex]}/>:<p>No dish is available to preview.</p>}</div><div className="print-label-sheet" aria-hidden="true">{printLabels.map((label,index)=><MealLabel key={`${label.index}-${label.copy}-${index}`} household={household} prepared={prepared} useBy={useBy} {...label} reheating={instructions[label.index]}/>)}</div></section>
}

function MealLabel({household,prepared,useBy,dish,copy,count,reheating}:{household:string;prepared:string;useBy:string;dish:LabelDish;copy:number;count:number;reheating:string}){return <article className="meal-label"><header><strong>DRIFTLINE AT HOME</strong><span title={household}>{household}</span></header><h3>{dish.title}</h3><div className="label-meta"><span><b>PREPARED</b>{dateLabel(prepared)}</span><span><b>USE BY</b>{dateLabel(useBy)}</span><span><b>CONTAINER</b>{copy+1} of {count}</span></div><p className="label-storage"><b>KEEP COLD:</b> Refrigerate at 40°F or below.</p><p className="label-reheat"><b>REHEAT:</b> <span>{reheating}</span></p><p className="label-allergens"><b>ALLERGENS:</b> <span>{dish.allergens.length?dish.allergens.join(", "):"None listed"}</span></p><footer><b>FOOD SAFETY:</b> <span>{dish.safety}</span></footer></article>}
