"use client";

import { useState } from "react";
import "./portal.css";

type Role = "customer" | "chef" | "admin";
type Notice = { title: string; detail: string } | null;

const recipes = [
  { name:"Cider-braised chicken", portions:12, active:35, total:95, allergens:"None", ingredients:[["Chicken thighs","6 lb"],["Yukon potatoes","4.5 lb"],["Apple cider","3 cups"],["Green beans","3 lb"]] },
  { name:"Coastal salmon cakes", portions:12, active:45, total:70, allergens:"Fish, egg", ingredients:[["Salmon","4.5 lb"],["Rice","4 cups"],["Eggs","6"],["Lemon","3"]] },
  { name:"Slow-cooked beef ragù", portions:12, active:30, total:180, allergens:"Dairy", ingredients:[["Beef chuck","5 lb"],["Tomatoes","6 cups"],["Polenta","4 cups"],["Carrots","3 lb"]] },
];

const customerTabs = ["Overview","Meals","Schedule","Household","Billing"];
const chefTabs = ["Today","Recipes","Time & Mileage","Earnings","Profile"];
const adminTabs = ["Dispatch","People","Recipe Library","Timecards","Finance","Safety","Reports"];

function Icon({ children }:{children:React.ReactNode}) { return <span className="p-icon" aria-hidden="true">{children}</span>; }
function Status({children,tone="green"}:{children:React.ReactNode;tone?:string}) { return <span className={`status ${tone}`}><i />{children}</span>; }

export default function Portal() {
  const [role,setRole] = useState<Role>("customer");
  const [tab,setTab] = useState("Overview");
  const [notice,setNotice] = useState<Notice>(null);
  const [clocked,setClocked] = useState(false);
  const [onBreak,setOnBreak] = useState(false);
  const [portions,setPortions] = useState(12);
  const [paused,setPaused] = useState(false);
  const [approved,setApproved] = useState(false);
  const [mealChecks,setMealChecks] = useState([true,true,false]);
  const [rating,setRating] = useState(0);
  const tabs = role==="customer"?customerTabs:role==="chef"?chefTabs:adminTabs;

  const changeRole=(next:Role)=>{
    setRole(next); setTab(next==="customer"?"Overview":next==="chef"?"Today":"Dispatch");
  };
  const toast=(title:string,detail:string)=>{setNotice({title,detail}); window.setTimeout(()=>setNotice(null),3500);};

  return <main className="portal">
    <header className="portal-top">
      <a className="portal-brand" href="/"><span>D</span><div><strong>DRIFTLINE</strong><small>AT HOME</small></div></a>
      <a className="staff-home-link" href="/account">← Customer site</a>
      <div className="role-switch" aria-label="Preview portal role">
        {(["customer","chef","admin"] as Role[]).map(item=><button key={item} className={role===item?"active":""} onClick={()=>changeRole(item)}>{item==="customer"?"Customer / Family":item==="chef"?"Chef":"Admin"}</button>)}
      </div>
      <a href="/cookbook" style={{fontSize:10,fontWeight:700,color:"#bd6643",textDecoration:"none"}}>100-recipe cookbook →</a>
      <div className="portal-user"><button aria-label="Notifications">●</button><span>{role==="customer"?"AB":role==="chef"?"MC":"DP"}</span><div><strong>{role==="customer"?"Ashley Barella":role==="chef"?"Maya Chen":"Driftline Ops"}</strong><small>{role==="customer"?"Household account":role==="chef"?"Approved chef":"Administrator"}</small></div></div>
    </header>
    <aside className="portal-side">
      <div className="side-title"><small>{role==="customer"?"MY HOUSEHOLD":role==="chef"?"CHEF WORKSPACE":"OPERATIONS"}</small><strong>{role==="customer"?"Barella Family":role==="chef"?"Tuesday · Aug 25":"North Coast"}</strong></div>
      <nav>{tabs.map((item,i)=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}><Icon>{["⌂","♨","□","◎","$","◷","↗"][i]||"·"}</Icon>{item}{item==="Safety"?<b>2</b>:null}</button>)}</nav>
      <div className="side-help"><strong>Need help?</strong><p>Driftline support is available every day.</p><button onClick={()=>toast("Support request started","An operations coordinator will contact you.")}>Contact support</button></div>
    </aside>
    <section className="portal-main">
      {role==="customer"?<Customer tab={tab} setTab={setTab} paused={paused} setPaused={setPaused} rating={rating} setRating={setRating} toast={toast}/>:
       role==="chef"?<Chef tab={tab} clocked={clocked} setClocked={setClocked} onBreak={onBreak} setOnBreak={setOnBreak} portions={portions} setPortions={setPortions} mealChecks={mealChecks} setMealChecks={setMealChecks} toast={toast}/>:
       <Admin tab={tab} approved={approved} setApproved={setApproved} toast={toast}/>}
    </section>
    {notice?<div className="toast"><span>✓</span><div><strong>{notice.title}</strong><small>{notice.detail}</small></div><button onClick={()=>setNotice(null)}>×</button></div>:null}
  </main>;
}

function Customer({tab,setTab,paused,setPaused,rating,setRating,toast}:{tab:string;setTab:(s:string)=>void;paused:boolean;setPaused:(v:boolean)=>void;rating:number;setRating:(v:number)=>void;toast:(a:string,b:string)=>void}) {
  if(tab==="Overview") return <Page title="Good morning, Ashley" sub="Your household is set for the week.">
    <div className="metric-row"><Metric label="NEXT VISIT" value="Tue, Sep 1" note="9:00 AM · Maya Chen" tone="sea"/><Metric label="CURRENT PACKAGE" value="Weekly · 12" note="$235 + groceries" tone="rust"/><Metric label="MEALS READY" value="12 portions" note="Prepared yesterday" tone="navy"/><Metric label="NEXT PAYMENT" value="$235.00" note="Due after next visit" tone="sand"/></div>
    <div className="portal-grid two"><Card title="This week’s meals" action="View menu" onAction={()=>setTab("Meals")}><div className="mini-meals">{recipes.map((r,i)=><div key={r.name}><span className={`mini-photo m${i+1}`}/><div><strong>{r.name}</strong><small>{[4,4,4][i]} portions · Ready to reheat</small></div><Status>Ready</Status></div>)}</div></Card>
    <Card title="Visit complete" action="View details" onAction={()=>toast("Visit details","3 dishes, 12 portions, kitchen cleanup confirmed.")}><div className="visit-complete"><span className="big-check">✓</span><div><strong>Maya finished at 12:42 PM</strong><p>3 dishes · 12 portions · Kitchen clean</p><small>Groceries: $84.62 · Receipt attached</small></div></div><div className="stars"><span>How was your visit?</span>{[1,2,3,4,5].map(n=><button key={n} onClick={()=>{setRating(n);toast("Thank you",`You rated this visit ${n} stars.`)}} className={n<=rating?"on":""}>★</button>)}</div></Card></div>
    <div className="portal-grid two"><Card title="Household notes"><ul className="check-list"><li><b>Allergy</b> No shellfish in the home</li><li><b>Preference</b> Low-sodium where possible</li><li><b>Dislike</b> No raw tomatoes</li><li><b>Access</b> Side-door keypad on file</li></ul></Card><Card title="Family update"><p className="message">“Your mom’s weekly meal prep is complete. Three dishes and 12 portions are labeled and refrigerated. The kitchen is clean. Next visit: Tuesday at 9:00 AM.”</p><Status>Sent to Jacquelyn</Status></Card></div>
  </Page>;
  if(tab==="Meals") return <Page title="Meals & preferences" sub="Choose from the rotating menu and help us learn your household."><div className="menu-cycle"><div><small>FALL CYCLE 01 · AUG 24–OCT 4</small><h2>Choose three entrées</h2><p>Six new dishes rotate approximately every six weeks.</p></div><Status>3 of 3 selected</Status></div><div className="choice-grid">{["Cider-braised chicken","Coastal salmon cakes","Slow-cooked beef ragù","Turkey meatloaf","Mushroom cottage pie","Lemon herb orzo"].map((name,i)=><button key={name} className={i<3?"meal-choice selected":"meal-choice"} onClick={()=>toast(i<3?"Meal saved":"Menu updated",name)}><span className={`choice-photo c${i+1}`}/><div><strong>{name}</strong><small>{i%2?"Freezer friendly":"Refrigerates well"} · {i%3?"Gluten-free option":"Dairy-free"}</small><p>{i<3?"Selected":"Add to this visit"} <b>{i<3?"✓":"+"}</b></p></div></button>)}</div><Card title="Favorites, dislikes & allergies"><div className="tags"><span>♥ Salmon</span><span>♥ Braised chicken</span><span className="no">× Raw tomatoes</span><span className="warn">! Shellfish allergy</span><button onClick={()=>toast("Preference editor opened","Household preferences are ready to update.")}>+ Add preference</button></div></Card></Page>;
  if(tab==="Schedule") return <Page title="Schedule" sub="Manage recurring visits, skips, and chef continuity."><div className="calendar-card"><div className="cal-head"><button>‹</button><strong>September 2026</strong><button>›</button></div><div className="calendar">{["S","M","T","W","T","F","S",...Array.from({length:30},(_,i)=>String(i+1))].map((d,i)=><span key={i} className={[9,16,23,30].includes(i)?"visit-day":""}>{d}{[9,16,23,30].includes(i)?<i/>:null}</span>)}</div></div><div className="portal-grid two"><Card title="Recurring service"><KeyRow label="Frequency" value="Every Tuesday"/><KeyRow label="Arrival window" value="9:00–9:30 AM"/><KeyRow label="Preferred chef" value="Maya Chen"/><KeyRow label="Backup coverage" value="Allowed"/><button className="outline-btn" onClick={()=>toast("Schedule editor opened","Choose a new recurring day or arrival window.")}>Edit schedule</button></Card><Card title="Service controls"><p>Pause upcoming visits without canceling your household account.</p><button className={paused?"primary-action sea":"primary-action"} onClick={()=>{setPaused(!paused);toast(paused?"Service resumed":"Service paused",paused?"Your Tuesday visits are active.":"No visits will be assigned until you resume.")}}>{paused?"Resume service":"Pause service"}</button><button className="text-action" onClick={()=>toast("Next visit skipped","September 1 was removed without changing the recurring schedule.")}>Skip next visit</button><button className="text-action" onClick={()=>toast("Reschedule opened","Available North Coast visit windows are displayed.")}>Reschedule next visit</button></Card></div></Page>;
  if(tab==="Household") return <Page title="Household profile" sub="Everything your chef needs for a safe, familiar visit."><div className="portal-grid two"><Card title="Primary household"><Field label="Service address" value="Astoria, Oregon 97103"/><Field label="Primary contact" value="Ashley Barella"/><Field label="Kitchen access" value="Side door · keypad instructions saved"/><Field label="Pets" value="One friendly dog"/><button className="outline-btn" onClick={()=>toast("Household editor opened","Address and access details can be updated.")}>Edit household</button></Card><Card title="Family & caregiver access"><Person name="Jacquelyn Barella" role="Visit updates · Can view meals" initials="JB"/><Person name="Casey Barella" role="Primary payer · Full access" initials="CB"/><button className="outline-btn" onClick={()=>toast("Invitation ready","Add an authorized family member or caregiver.")}>+ Invite family member</button></Card></div><Card title="Safety & dietary profile"><div className="safety-grid"><Field label="Allergies" value="Shellfish — do not bring into home"/><Field label="Provider instructions" value="Low-sodium preference (non-medical)"/><Field label="Emergency contact" value="Casey · number verified"/><Field label="Kitchen notes" value="Induction cooktop · knives available"/></div><p className="disclaimer">Driftline records household instructions but does not provide medical nutrition treatment or make medical claims.</p></Card></Page>;
  return <Page title="Billing & groceries" sub="Service fees, grocery receipts, family payer, and payment history."><div className="metric-row"><Metric label="SERVICE THIS MONTH" value="$940.00" note="4 Weekly visits" tone="navy"/><Metric label="GROCERIES" value="$326.48" note="Actual cost · 4 receipts" tone="sea"/><Metric label="CREDITS" value="$0.00" note="No account credits" tone="sand"/><Metric label="AUTOPAY" value="On" note="Visa ending 4242" tone="rust"/></div><div className="portal-grid two"><Card title="Payment method"><div className="payment-card"><span>VISA</span><strong>•••• •••• •••• 4242</strong><small>Casey Barella · Expires 08/29</small></div><button className="outline-btn" onClick={()=>toast("Payment editor opened","Update the household payment method or payer.")}>Manage payment</button></Card><Card title="Latest grocery receipt"><KeyRow label="Safeway · Astoria" value="$84.62"/><KeyRow label="Uploaded by" value="Maya Chen"/><KeyRow label="Status" value="Approved & reimbursed"/><button className="outline-btn" onClick={()=>toast("Receipt opened","18 grocery line items are available for review.")}>View receipt</button></Card></div><Card title="Transactions"><Table heads={["Date","Description","Type","Status","Amount"]} rows={[["Aug 25","Weekly · 12 portions","Service","Paid","$235.00"],["Aug 25","Safeway receipt","Groceries","Reimbursed","$84.62"],["Aug 18","Weekly · 12 portions","Service","Paid","$235.00"],["Aug 18","Fred Meyer receipt","Groceries","Reimbursed","$79.41"]]}/></Card></Page>;
}

function Chef({tab,clocked,setClocked,onBreak,setOnBreak,portions,setPortions,mealChecks,setMealChecks,toast}:{tab:string;clocked:boolean;setClocked:(v:boolean)=>void;onBreak:boolean;setOnBreak:(v:boolean)=>void;portions:number;setPortions:(v:number)=>void;mealChecks:boolean[];setMealChecks:(v:boolean[])=>void;toast:(a:string,b:string)=>void}) {
  if(tab==="Today") return <Page title="Today’s route" sub="Tuesday, August 25 · Two households"><div className={`clock-banner ${clocked?"active":""}`}><div><small>DAY TIMECARD</small><strong>{clocked?(onBreak?"On break · 00:18":"Clocked in · 03:42:16"):"Not clocked in"}</strong><p>Shopping, inter-client travel, and job time are recorded.</p></div><div>{clocked?<button className="break-btn" onClick={()=>{setOnBreak(!onBreak);toast(onBreak?"Break ended":"Break started","Your actual timecard has been updated.")}}>{onBreak?"End break":"Start break"}</button>:null}<button className="clock-btn" onClick={()=>{setClocked(!clocked);setOnBreak(false);toast(clocked?"Day complete":"Day started",clocked?"Your timecard was submitted for review.":"GPS and mileage tracking are active.")}}>{clocked?"Clock out":"Clock in for day"}</button></div></div><Card title="9:00 AM · Barella household"><div className="job-head"><div><Status>In progress</Status><h2>Weekly · 12 portions</h2><p>Astoria · 4.2 miles away · Side door access</p></div><button className="primary-action" onClick={()=>toast("Job timeline updated","Arrival, GPS location, and job start were recorded.")}>Arrive & start job</button></div><div className="job-steps">{["Shopping complete","Arrived & checked in","Kitchen safety check","Cook & portion meals","Label & photograph","Cleanup attestation","Send family update"].map((s,i)=><button key={s} className={i<3?"done":""} onClick={()=>toast("Task recorded",s)}><span>{i<3?"✓":i+1}</span>{s}</button>)}</div><div className="alert-line"><b>!</b><span><strong>Shellfish allergy</strong>Do not bring shellfish into this household.</span></div></Card><Card title="1:00 PM · Morrison household"><div className="job-head"><div><Status tone="gray">Upcoming</Status><h2>Classic · 8 portions</h2><p>Seaside · 16.8 compensable travel miles</p></div><button className="outline-btn" onClick={()=>toast("Navigation ready","Route and travel tracking are prepared.")}>View route</button></div></Card></Page>;
  if(tab==="Recipes") { const base=recipes[0]; const factor=portions/base.portions; return <Page title="Recipe book" sub="Standardized recipes, approved scales, safety, and pairing efficiency."><div className="recipe-layout"><aside className="recipe-list"><input placeholder="Search 64 recipes…" />{recipes.map((r,i)=><button key={r.name} className={i===0?"active":""}><span className={`recipe-thumb r${i+1}`}/><div><strong>{r.name}</strong><small>{r.active} min active · {r.allergens}</small></div></button>)}</aside><article className="recipe-card"><div className="recipe-hero"><div><Status>Approved recipe</Status><h2>{base.name}</h2><p>Pairs efficiently with slow-cooked beef ragù.</p></div><div className="scale-control"><label>PORTIONS</label><button onClick={()=>setPortions(Math.max(2,portions-2))}>−</button><strong>{portions}</strong><button onClick={()=>setPortions(portions+2)}>+</button></div></div><div className="recipe-meta"><span><small>ACTIVE</small>{base.active} min</span><span><small>TOTAL</small>{base.total} min</span><span><small>EQUIPMENT</small>Oven · 2 burners</span><span><small>ALLERGENS</small>{base.allergens}</span></div><h3>Scaled ingredients</h3><div className="ingredients">{base.ingredients.map(([n,a])=><div key={n}><span>{n}</span><strong>{a.replace(/[0-9.]+/,m=>(Number(m)*factor).toFixed(1).replace(".0",""))}</strong></div>)}</div><div className="recipe-notes"><div><h3>Food safety</h3><p>Cook chicken to 165°F. Cool portions promptly and refrigerate within two hours.</p></div><div><h3>Storage & reheating</h3><p>Refrigerate up to four days. Reheat covered to 165°F.</p></div></div><button className="primary-action" onClick={()=>toast("Recipe added","Scaled ingredients were added to today’s consolidated shopping list.")}>Add scaled recipe to job</button></article></div></Page>;}
  if(tab==="Time & Mileage") return <Page title="Time & mileage" sub="Daily hours, breaks, shopping, jobs, travel, and corrections."><div className="metric-row"><Metric label="THIS WEEK" value="26h 18m" note="All compensable time" tone="navy"/><Metric label="MILEAGE" value="74.6 mi" note="Inter-client & approved" tone="sea"/><Metric label="BREAKS" value="1h 12m" note="Recorded unpaid" tone="sand"/><Metric label="EST. PAY" value="$812.00" note="Before mileage" tone="rust"/></div><Card title="Tuesday timecard"><Table heads={["Activity","Start","End","Duration","Status"]} rows={[["Shopping · Barella","8:10 AM","8:46 AM","0:36","GPS verified"],["Barella household","9:01 AM","12:42 PM","3:41","Completed"],["Break","12:42 PM","1:00 PM","0:18","Recorded"],["Travel · Astoria→Seaside","1:00 PM","1:32 PM","0:32","16.8 miles"],["Morrison household","1:33 PM","—","In progress","Live"]]}/><button className="outline-btn" onClick={()=>toast("Correction requested","The original entry remains in the audit trail pending admin review.")}>Request time correction</button></Card><Card title="GPS job timeline"><div className="timeline">{["8:10 Shopping started · Astoria Safeway","8:46 Receipt uploaded · $84.62","9:01 Arrived · Barella household","12:42 Job completed · family update sent","1:00 Compensable travel started","1:32 Arrived · Morrison household"].map((x,i)=><p key={x}><i className={i<5?"done":""}/>{x}</p>)}</div></Card></Page>;
  if(tab==="Earnings") return <Page title="Earnings" sub="Package pay, actual-hours compliance, mileage, and payment history."><div className="metric-row"><Metric label="CURRENT PERIOD" value="$812.00" note="6 completed jobs" tone="rust"/><Metric label="MILEAGE" value="$49.98" note="74.6 approved miles" tone="sea"/><Metric label="NEXT PAYDAY" value="Sep 4" note="Direct deposit" tone="navy"/><Metric label="YTD" value="$18,420" note="Gross earnings" tone="sand"/></div><Card title="Job-based earnings"><Table heads={["Date","Household","Package","Actual time","Job pay"]} rows={[["Aug 25","Barella","Weekly · 12","3h 41m","$126.00"],["Aug 25","Morrison","Classic · 8","—","$94.00"],["Aug 24","Nguyen","Household · 20","5h 08m","$164.00"],["Aug 22","Franklin","Essential · 6","2h 56m","$82.00"]]}/></Card><Card title="Compliance note"><p className="message">Package-based job pay never replaces actual-hours, overtime, break, and compensable-travel tracking. Driftline reviews every pay period against recorded time.</p></Card></Page>;
  return <Page title="Chef profile & credentials" sub="Qualifications, availability, service area, and marketplace standing."><div className="profile-hero"><span>MC</span><div><h2>Maya Chen</h2><p>Approved Driftline chef · Seafood & family meals</p><Status>Available for matching</Status></div><div className="rating-box"><strong>4.9</strong><small>38 household ratings</small></div></div><div className="portal-grid two"><Card title="Credentials"><Credential name="Oregon Food Handler" date="Valid through May 2028"/><Credential name="Background check" date="Cleared July 2026"/><Credential name="References" date="3 verified"/><Credential name="In-home safety training" date="Completed August 2026"/></Card><Card title="Availability & area"><KeyRow label="Regular days" value="Tue–Sat"/><KeyRow label="Daily capacity" value="2 compatible households"/><KeyRow label="Service area" value="Astoria to Cannon Beach"/><KeyRow label="Same-chef clients" value="8 households"/><button className="outline-btn" onClick={()=>toast("Availability editor opened","Update days, blackout dates, or service radius.")}>Edit availability</button></Card></div></Page>;
}

function Admin({tab,approved,setApproved,toast}:{tab:string;approved:boolean;setApproved:(v:boolean)=>void;toast:(a:string,b:string)=>void}) {
  if(tab==="Dispatch") return <Page title="Dispatch board" sub="Tuesday, August 25 · North Coast operations"><div className="metric-row"><Metric label="TODAY’S VISITS" value="18" note="12 complete · 4 active · 2 next" tone="navy"/><Metric label="ON-TIME ARRIVAL" value="94%" note="Across all chefs" tone="sea"/><Metric label="UNASSIGNED" value="2" note="Needs coverage" tone="rust"/><Metric label="INCIDENTS" value="1 open" note="Low severity" tone="sand"/></div><div className="dispatch-board">{["Unassigned · 2","Shopping · 2","In progress · 4","Completed · 12"].map((col,i)=><section key={col}><h3>{col}</h3>{Array.from({length:i===3?3:2},(_,j)=><article key={j}><Status tone={i===0?"rust":i===3?"green":"sea"}>{i===0?"Coverage needed":i===3?"Complete":i===1?"Shopping":"In home"}</Status><strong>{["Morrison","Barella","Nguyen","Franklin","Delgado"][i+j]} household</strong><small>{["Classic · 8","Weekly · 12","Household · 20"][j%3]}</small><p>{["Seaside · 1:00 PM","Astoria · 9:00 AM","Gearhart · 10:30 AM"][j%3]}</p><button onClick={()=>toast("Assignment opened","Chef matching, route, household notes, and job status are available.")}>Manage</button></article>)}</section>)}</div></Page>;
  if(tab==="People") return <Page title="People & credentials" sub="Customers, family payers, chefs, access, and qualification status."><div className="segmented"><button className="active">Chefs · 14</button><button>Households · 86</button><button>Family payers · 34</button><button>Applicants · 6</button></div><Card title="Chef roster"><Table heads={["Chef","Status","Credentials","Households","Rating","Action"]} rows={[["Maya Chen","Active","All current","8","4.9","View"],["Jordan Lee","Active","All current","7","4.8","View"],["Alex Morgan","Review","Food handler: 18 days","5","4.7","Renew"],["Sam Rivera","Applicant","Background pending","—","—","Review"]]}/></Card><div className="portal-grid two"><Card title="Chef approval checklist"><ul className="approval-list"><li className="done">Identity verified</li><li className="done">Background check cleared</li><li className="done">Three references verified</li><li>Food-handler credential</li><li>In-home safety training</li><li>Service-area confirmation</li></ul><button className="primary-action" onClick={()=>toast("Application updated","Chef approval status and audit history were saved.")}>Review applicant</button></Card><Card title="Credential alerts"><Alert title="Alex Morgan" text="Food-handler card expires in 18 days" tone="warn"/><Alert title="Jamie Patel" text="Background recheck due September 12" tone="gray"/></Card></div></Page>;
  if(tab==="Recipe Library") return <Page title="Recipe library" sub="64 standardized recipes · seasonal cycles · approved scaling."><div className="library-tools"><input placeholder="Search recipes…" /><select><option>All seasons</option><option>Fall cycle</option><option>Winter cycle</option></select><select><option>All dietary tags</option><option>Gluten-free</option><option>Dairy-free</option></select><button className="primary-action" onClick={()=>toast("Recipe editor opened","Create ingredients, scales, timings, safety, storage, and photos.")}>+ New recipe</button></div><Card title="Published recipes"><Table heads={["Recipe","Cycle","Approved scales","Active / total","Allergens","Status"]} rows={recipes.map(r=>[r.name,"Fall 01","6, 8, 12, 16, 20, 24",`${r.active}m / ${r.total}m`,r.allergens,"Published"])}/></Card><div className="portal-grid three"><Metric label="LIBRARY TARGET" value="64 / 75" note="First-year recipes" tone="navy"/><Metric label="NEEDS PHOTOS" value="7" note="Drafts blocked" tone="rust"/><Metric label="PAIRING REVIEW" value="4" note="Efficiency check" tone="sea"/></div></Page>;
  if(tab==="Timecards") return <Page title="Timecards & payroll review" sub="Actual hours, breaks, travel, mileage, corrections, and overtime."><div className="metric-row"><Metric label="PENDING REVIEW" value="6" note="2 corrections included" tone="rust"/><Metric label="WEEKLY HOURS" value="314.8" note="14 active chefs" tone="navy"/><Metric label="OVERTIME" value="3.2h" note="1 chef flagged" tone="sand"/><Metric label="MILEAGE" value="842 mi" note="$564.14 estimated" tone="sea"/></div><Card title="Timecard review · Maya Chen"><Table heads={["Activity","Recorded","GPS / receipt","Pay treatment","Status"]} rows={[["Shopping","0:36","Receipt + location","Compensable","Verified"],["Barella job","3:41","Job timeline","Package pay check","Verified"],["Break","0:18","Manual","Unpaid","Recorded"],["Inter-client travel","0:32 / 16.8 mi","GPS verified","Compensable","Verified"],["Correction request","+0:12","Chef note","Pending review",approved?"Approved":"Review"]]}/><div className="approval-actions"><button className="outline-btn" onClick={()=>toast("Correction returned","The chef will receive your requested clarification.")}>Request details</button><button className="primary-action" disabled={approved} onClick={()=>{setApproved(true);toast("Timecard approved","The correction, audit trail, payroll time, and mileage were updated.")}}>{approved?"Approved ✓":"Approve timecard"}</button></div></Card><Card title="Audit trail"><div className="audit"><p><b>Aug 25 · 4:18 PM</b>Chef requested +12 minute correction: customer safety walkthrough.</p><p><b>Aug 25 · 4:19 PM</b>Original clock event preserved. Admin review opened.</p>{approved?<p><b>Just now</b>Correction approved by Driftline Ops.</p>:null}</div></Card></Page>;
  if(tab==="Finance") return <Page title="Finance" sub="Service revenue, grocery pass-through, chef pay, refunds, and disputes."><div className="metric-row"><Metric label="AUG SERVICE FEES" value="$31,480" note="+18% vs July" tone="navy"/><Metric label="GROCERY PASS-THROUGH" value="$9,842" note="Receipts reconciled" tone="sea"/><Metric label="CHEF PAY" value="$16,726" note="Jobs + compliance true-up" tone="rust"/><Metric label="REFUNDS / CREDITS" value="$235" note="0.7% of fees" tone="sand"/></div><Card title="Payment operations"><Table heads={["Household","Service","Groceries","Payment","Chef pay","Status"]} rows={[["Barella","$235.00","$84.62","Autopay","$126.00","Settled"],["Morrison","$195.00","Pending","Autopay","$94.00","Visit active"],["Nguyen","$325.00","$112.08","Family payer","$164.00","Settled"],["Franklin","$175.00","$68.41","Autopay","$82.00","Settled"]]}/></Card><div className="portal-grid two"><Card title="Receipt queue"><Alert title="2 receipts need review" text="One total mismatch · one image needs replacement" tone="warn"/><button className="outline-btn" onClick={()=>toast("Receipt queue opened","Review actual grocery costs and chef reimbursement.")}>Review receipts</button></Card><Card title="Disputes & adjustments"><Alert title="One open credit request" text="Customer reported one damaged meal container" tone="gray"/><button className="outline-btn" onClick={()=>toast("Adjustment opened","Refund, credit, and dispute history are available.")}>Manage adjustments</button></Card></div></Page>;
  if(tab==="Safety") return <Page title="Safety & incidents" sub="Allergies, household risks, incident response, and documented follow-up."><div className="metric-row"><Metric label="OPEN INCIDENTS" value="2" note="0 urgent" tone="rust"/><Metric label="ALLERGY FLAGS" value="28" note="Across 86 households" tone="sand"/><Metric label="CREDENTIAL ALERTS" value="3" note="Within 30 days" tone="sea"/><Metric label="SAFETY COMPLETION" value="98%" note="This month" tone="navy"/></div><Card title="Incident queue"><div className="incident"><Status tone="rust">Open · Low severity</Status><h3>Damaged meal container</h3><p>Barella household · Reported by customer · Aug 25, 2:10 PM</p><button onClick={()=>toast("Incident opened","Photos, statements, follow-up, and resolution controls are available.")}>Review incident</button></div><div className="incident"><Status tone="gray">Investigating</Status><h3>Kitchen trip hazard documented</h3><p>Franklin household · Reported by chef · Aug 24, 10:18 AM</p><button onClick={()=>toast("Safety follow-up opened","Household warning and chef notes are ready.")}>Review incident</button></div></Card><div className="portal-grid two"><Card title="Allergy controls"><p className="message">Allergy flags appear on dispatch cards, chef job details, shopping lists, recipes, and arrival safety checks.</p><button className="outline-btn" onClick={()=>toast("Allergy audit opened","Review acknowledgements and recipe conflicts.")}>Run allergy audit</button></Card><Card title="Report an incident"><select><option>Food safety</option><option>Injury or hazard</option><option>Property concern</option><option>Allergy concern</option></select><textarea placeholder="Document what happened…" /><button className="primary-action" onClick={()=>toast("Incident draft saved","Add people, photos, and severity before filing.")}>Create incident draft</button></Card></div></Page>;
  return <Page title="Reports & marketplace health" sub="Growth, continuity, efficiency, quality, and compliance."><div className="metric-row"><Metric label="ACTIVE HOUSEHOLDS" value="86" note="+12 this month" tone="navy"/><Metric label="ACTIVE CHEFS" value="14" note="6 applicants" tone="sea"/><Metric label="SAME-CHEF RATE" value="91%" note="Continuity target: 90%" tone="rust"/><Metric label="AVG RATING" value="4.86" note="412 completed visits" tone="sand"/></div><div className="portal-grid two"><Card title="Visits by week"><div className="bars">{[42,56,61,72,78,86].map((n,i)=><div key={i}><span style={{height:`${n}%`}}/><small>W{i+1}</small></div>)}</div></Card><Card title="Operating quality"><KeyRow label="On-time arrival" value="94%"/><KeyRow label="Two-household day utilization" value="72%"/><KeyRow label="Receipt reconciliation" value="98%"/><KeyRow label="Cleanup attestations" value="100%"/><KeyRow label="Open incidents" value="2"/></Card></div><Card title="Pilot and compliance exports"><div className="export-row">{["Time & overtime","Mileage & travel","Grocery costs","Dishes & portions","Cleanup & safety","Ratings & feedback"].map(x=><button key={x} onClick={()=>toast("Report prepared",`${x} data is ready for export.`)}>↓ {x}</button>)}</div></Card></Page>;
}

function Page({title,sub,children}:{title:string;sub:string;children:React.ReactNode}) { return <><header className="page-head"><div><h1>{title}</h1><p>{sub}</p></div><span className="live-dot">● Live workspace</span></header><div className="page-body">{children}</div></>; }
function Card({title,action,onAction,children}:{title:string;action?:string;onAction?:()=>void;children:React.ReactNode}) { return <section className="p-card"><header><h3>{title}</h3>{action?<button onClick={onAction}>{action} →</button>:null}</header>{children}</section>; }
function Metric({label,value,note,tone}:{label:string;value:string;note:string;tone:string}) { return <div className={`metric ${tone}`}><small>{label}</small><strong>{value}</strong><span>{note}</span></div>; }
function KeyRow({label,value}:{label:string;value:string}) { return <div className="key-row"><span>{label}</span><strong>{value}</strong></div>; }
function Field({label,value}:{label:string;value:string}) { return <label className="read-field"><span>{label}</span><strong>{value}</strong></label>; }
function Person({name,role,initials}:{name:string;role:string;initials:string}) { return <div className="person"><i>{initials}</i><div><strong>{name}</strong><small>{role}</small></div><button>•••</button></div>; }
function Credential({name,date}:{name:string;date:string}) { return <div className="credential"><span>✓</span><div><strong>{name}</strong><small>{date}</small></div><Status>Current</Status></div>; }
function Alert({title,text,tone}:{title:string;text:string;tone:string}) { return <div className={`alert ${tone}`}><span>!</span><div><strong>{title}</strong><small>{text}</small></div></div>; }
function Table({heads,rows}:{heads:string[];rows:string[][]}) { return <div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>; }
