import {NextResponse} from "next/server";
import {getChatGPTUser} from "../../chatgpt-auth";
import {createEvent,deleteEvent,listEvents,updateEvent} from "../../../db/schedule";
export const dynamic="force-dynamic";
function clean(body:Record<string,unknown>){const text=(key:string,limit=500)=>String(body[key]??"").trim().slice(0,limit);return{serviceDate:text("serviceDate",10),startTime:text("startTime",5),endTime:text("endTime",5),household:text("household",120),chef:text("chef",100)||"Unassigned",packageName:text("packageName",50)||"Weekly",location:text("location",160),status:text("status",30)||"scheduled",notes:text("notes",1000)}}
export async function GET(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:"Staff sign-in required"},{status:401});const url=new URL(request.url);const start=url.searchParams.get("start")??"2000-01-01",end=url.searchParams.get("end")??"2100-12-31";return NextResponse.json(await listEvents(start,end))}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:"Staff sign-in required"},{status:401});const event=clean(await request.json() as Record<string,unknown>);if(!event.serviceDate||!event.startTime||!event.household)return NextResponse.json({error:"Date, time, and household are required"},{status:400});return NextResponse.json(await createEvent(user.email,event),{status:201})}
export async function PUT(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:"Staff sign-in required"},{status:401});const body=await request.json() as Record<string,unknown>,id=Number(body.id),event=clean(body);if(!id||!event.serviceDate||!event.startTime||!event.household)return NextResponse.json({error:"Invalid visit"},{status:400});return NextResponse.json(await updateEvent(id,event))}
export async function DELETE(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:"Staff sign-in required"},{status:401});await deleteEvent(Number(new URL(request.url).searchParams.get("id")));return NextResponse.json({ok:true})}
