export const DISCLOSURE_VERSION="2026-08-26";
export const customerSections=[
  {title:"In-home personal-chef service",body:"Driftline At Home prepares food only in the customer’s home kitchen for the customer and their non-paying guests. Food is not prepared or stored in advance at a Driftline or chef residence. The customer must provide safe, lawful access to the home and a reasonably clean, working kitchen with potable water, electricity, refrigeration, and functioning appliances."},
  {title:"Allergies and dietary instructions",body:"Customers must disclose known allergies, intolerances, ingredient restrictions, and relevant household instructions before service and promptly update changes. Driftline takes reasonable precautions, but a residential kitchen may contain shared equipment, surfaces, and ingredients; an allergen-free environment cannot be guaranteed. Driftline does not diagnose, prescribe, or provide medical nutrition therapy. Medical dietary instructions should come from a qualified healthcare professional."},
  {title:"Groceries, substitutions, and charges",body:"Groceries are separate from the personal-chef service fee. Depending on the selected plan, the customer may fund groceries directly or authorize Driftline or the assigned chef to purchase approved ingredients. Product availability, substitutions, actual receipts, grocery estimates, reimbursements, refunds, tips, service fees, and chef compensation are recorded separately. Any future tiered grocery charge will be disclosed before the customer confirms a visit."},
  {title:"Food storage and customer responsibility",body:"Driftline labels prepared food with available storage and reheating instructions. Customers are responsible for promptly refrigerating food, maintaining refrigeration at 40°F or below, following labels, reheating cooked food to 165°F where instructed, and discarding food that has been left unrefrigerated or kept beyond its labeled use period."},
  {title:"Home safety, pets, property, and communication",body:"Customers must identify hazards, access conditions, pets, security systems, household members, and special property instructions. Unsafe conditions may require a visit to pause or end. Driftline may communicate visit status and meal information only with contacts authorized on the account. Emergencies, injuries, property damage, suspected foodborne illness, or safety concerns should be reported promptly."},
  {title:"Scheduling and policies",body:"Arrival windows, cancellations, rescheduling, grocery approvals, payment authorization, refunds, and credits are governed by the policy shown when a visit is booked. Nothing in these disclosures waives rights or responsibilities that cannot lawfully be waived. Driftline may update these terms and will request a new acceptance when material changes are made."},
];
export const chefSections=[
  {title:"Authorized in-home service only",body:"Chefs may prepare and store customer food only in the assigned customer’s home kitchen, for that customer and non-paying guests. No customer food may be prepared or stored in advance at the chef’s home or another unapproved location. Ingredients must come from approved sources. Chefs may use approved equipment, utensils, and spices according to Driftline policy."},
  {title:"Food safety and allergens",body:"Chefs must maintain required food-handler credentials, review the household profile before every visit, prevent cross-contact, use safe temperatures, label and cool food promptly, and follow Driftline sanitation procedures. An allergy conflict, unsafe kitchen, temperature problem, contamination concern, illness, or suspected foodborne illness must be reported immediately; service must stop when safe preparation cannot be assured."},
  {title:"Time, breaks, travel, and mileage",body:"All work time must be recorded accurately, including required shopping, customer job time, required waiting, and compensable travel between job sites. No off-the-clock work is permitted. Meal and rest periods must be recorded and taken according to applicable law and Driftline policy. Package or job-based pay does not replace minimum-wage, overtime, or actual-hours review. Mileage records must be truthful and supported when requested."},
  {title:"Customer homes, privacy, and conduct",body:"Chefs must follow documented access instructions, respect customer property and privacy, maintain professional boundaries, secure keys and codes, avoid unauthorized guests or photography, and share customer information only through authorized Driftline workflows. Harassment, discrimination, retaliation, theft, impairment, violence, or misuse of confidential information is prohibited."},
  {title:"Incidents and documentation",body:"Injury, property damage, vehicle incidents during work, threats, unsafe conditions, lost access credentials, suspected abuse or exploitation, customer complaints, food-safety events, and emergency-service contact must be reported promptly. Records, receipts, photographs, time entries, and attestations must be accurate; original records may be retained in the audit trail when corrected."},
  {title:"Employment and protected rights",body:"These acknowledgments supplement—not replace—the chef’s employment documents, safety training, compensation plan, workers’ compensation coverage, and applicable law. They do not require a chef to waive wages, protected leave, workplace-safety rights, anti-discrimination protections, the right to report concerns, or other rights that cannot lawfully be waived. Material updates require a new acceptance."},
];
